name: 'Build and deploy API'

on:
  push:
    branches:
    - 'main'

jobs:
  build-api-image:
    name: Setup and Build
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Build
      run: |-
        gcloud builds submit api \
          --region=us-west2 \
          --tag us-west2-docker.pkg.dev/mysite-360701/docker/api:$GITHUB_SHA