name: 'API'

on:
  push:
    branches:
    - 'main'

env:
  PROJECT: mysite-360701
  REGION: us-central1
  DOCKER_ARTIFACT_PATH: docker
  TERRAFORM_STATE_BUCKET: terraform-state-lrrthzu
  TF_VAR_PROJECT: mysite-360701
  TF_VAR_REGION: us-central1
  TF_VAR_DOCKER_ARTIFACT_PATH: docker
  TF_VAR_TERRAFORM_STATE_BUCKET: terraform-state-lrrthzu

jobs:
  infraestructure:
    name: Provisioning
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: infra

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - name: Setup GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Create GCP Store
      run: |-
        gsutil ls gs://$TERRAFORM_STATE_BUCKET \
        2>/dev/null || \
        gsutil mb \
        -l $REGION \
        gs://$TERRAFORM_STATE_BUCKET

    - name: Inicialization
      run: |-
        terraform init \
        -backend-config="bucket=$TERRAFORM_STATE_BUCKET"

    - name: Apply
      run: terraform apply -auto-approve
  
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    needs: infraestructure

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - name: Setup GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Build
      run: |-
        gcloud builds submit api \
          --region=$REGION \
          --tag $REGION-docker.pkg.dev/$PROJECT/$DOCKER_ARTIFACT_PATH/api:$GITHUB_SHA

    - name: Deploy
      run: |-
        gcloud run deploy api \
          --region $REGION \
          --image $REGION-docker.pkg.dev/$PROJECT/$DOCKER_ARTIFACT_PATH/api:$GITHUB_SHA