name: 'API'

on:
  push:
    branches:
    - 'main'

env:
  PROJECT: mysite-360701
  DOCKER_ARTIFACT_PATH: docker
  TF_VAR_PROJECT: mysite-360701

jobs:
  infraestructure:
    name: Provisioning
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: infra

    steps:    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - name: Setup GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Inicialization
      run: terraform init

    - name: Apply
      run: terraform apply -auto-approve
  
  build:
    needs: infraestructure
    name: Setup and Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - name: Setup GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Build
      run: |-
        gcloud builds submit api \
          --region=us-west2 \
          --tag us-west2-docker.pkg.dev/$PROJECT/$DOCKER_ARTIFACT_PATH/api:$GITHUB_SHA