name: 'Main'

on:
  push:
    branches:
    - 'main'

env:
  project: mysite-360701
  region: us-central1
  terraform_state: terraform-state-lrrthzu
  TF_VAR_PROJECT: mysite-360701
  TF_VAR_REGION: us-central1

jobs:
  terraform-state:
    name: Setup Terraform state
    runs-on: ubuntu-latest
    env:
      bucket: gs://${{terraform_state}}
    
    steps:
    - name: Authenticate
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - name: Setup GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Setup Terraform state
      run: |-
        gsutil ls ${{env.bucket}} 2>/dev/null || \
        gsutil mb -l ${{env.region}} ${{env.bucket}}

  build-api:
    name: Build and push API image
    runs-on: ubuntu-latest
    env:
      image: ${{env.region}}-docker.pkg.dev/${{env.project}}/docker/api:$GITHUB_SHA

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - name: Setup GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Build
      run: |-
        gcloud builds submit api \
          --region=${{env.region}} \
          --tag ${{env.image}}
  
  infraestructure:
    name: Provisioning
    runs-on: ubuntu-latest
    needs: [
      terraform-state,
      build-api
    ]

    defaults:
      run:
        shell: bash
        working-directory: infra

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - name: Setup GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Inicialization
      run: |-
        terraform init \
        -backend-config="bucket=${{env.terraform_state}}"

    - name: Apply
      run: terraform apply -auto-approve