name: 'Main'

on:
  push:
    branches:
    - 'main'

env:
  project: mysite-360701
  region: us-central1
  terraform_state: terraform-state-lrrthzu
  docker_repository: docker

jobs:
  docker-repository:
    name: Setup Docker repository
    runs-on: ubuntu-latest
    
    steps:    
    - name: Authenticate
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - name: Setup GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Setup repository
      run: |-
        gcloud artifacts repositories create $docker_repository \
          --location us-central1 \
          --repository-format docker \
          2>/dev/null || true
  
  terraform-state-bucket:
    name: Setup Terraform state bucket
    runs-on: ubuntu-latest
    
    steps:
    - name: Custom env variables
      run: |-
        echo "bucket=gs://${{env.terraform_state}}" >> $GITHUB_ENV
    
    - name: Authenticate
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - name: Setup GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Setup Terraform state
      run: |-
        gsutil ls $bucket 2>/dev/null || \
        gsutil mb -l $region $bucket

  build-api:
    name: Build and push API image
    runs-on: ubuntu-latest
    needs: [
      docker-repository
    ]

    steps:    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - name: Setup GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Build
      run: |-
        cd api && \
        gcloud builds submit \
          --region $region \
          --tag $region-docker.pkg.dev/$project/$docker_repository/api:latest
  
  infraestructure:
    name: Provisioning
    runs-on: ubuntu-latest
    needs: [
      docker-repository,
      terraform-state-bucket,
      build-api
    ]

    defaults:
      run:
        shell: bash

    steps:
    - name: Custom env variables
      run: |-
        echo "TF_VAR_project=${{env.project}}" >> $GITHUB_ENV && \
        echo "TF_VAR_region=${{env.region}}" >> $GITHUB_ENV && \
        echo "TF_VAR_api_image=${{env.region}}-docker.pkg.dev/${{env.project}}/${{env.docker_repository}}/api:latest" >> $GITHUB_ENV
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{secrets.SA_KEY}}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Inicialization
      run: |-
        cd infra && \
        terraform init \
        -backend-config="bucket=$terraform_state"

    - name: Apply
      run: |-
        cd infra && \
        terraform apply -auto-approve