name: 'Main'

on:
  push:
    branches:
    - 'main'

env:
  project: mysite-360701
  region: us-central1
  terraform_state: terraform-state-lrrthzu
  docker_artifact_path: docker

jobs:
  terraform-state:
    name: Setup Terraform state
    runs-on: ubuntu-latest
    
    steps:
    - name: Custom env variables
      run: |-
        echo "bucket=gs://${{env.terraform_state}}" >> $GITHUB_ENV
    
    - name: Authenticate
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - name: Setup GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Setup Terraform state
      run: |-
        gsutil ls $bucket 2>/dev/null || \
        gsutil mb -l $region $bucket

  build-api:
    name: Build and push API image
    runs-on: ubuntu-latest

    steps:
    - name: Custom env variables
      run: |-
        echo "image=${{env.region}}-docker.pkg.dev/${{env.project}}/docker/api:latest" >> $GITHUB_ENV
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - name: Setup GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Build
      run: |-
        gcloud builds submit api \
          --region=$region \
          --tag $image
  
  infraestructure:
    name: Provisioning
    runs-on: ubuntu-latest
    needs: [
      terraform-state,
      build-api
    ]

    defaults:
      run:
        shell: bash

    steps:
    - name: Custom env variables
      run: |-
        echo "TF_VAR_project=${{env.project}}" >> $GITHUB_ENV && \
        echo "TF_VAR_region=${{env.region}}" >> $GITHUB_ENV && \
        echo "TF_VAR_docker_artifact_path=${{env.docker_artifact_path}}" >> $GITHUB_ENV
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{secrets.SA_KEY}}

    - name: Setup GCP Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Inicialization
      run: |-
        cd infra && \
        terraform init \
        -backend-config="bucket=$terraform_state"

    - name: Apply
      run: |-
        cd infra && \
        terraform apply -auto-approve